# /etc/fail2ban/action.d/iptables-docker.conf

[Definition]
# Ensure DOCKER-USER exists and has a return at top
actionstart = \
    iptables -w -N DOCKER-USER || true; \
    iptables -w -C DOCKER-USER -j RETURN || iptables -w -I DOCKER-USER -j RETURN

actionstop = \
    iptables -w -D DOCKER-USER -j RETURN || true; \
    iptables -w -X DOCKER-USER || true

# On ban, insert at top of DOCKER-USER
actionban   = iptables -w -I DOCKER-USER 1 -s <ip> -j REJECT --reject-with tcp-reset
actionunban = iptables -w -D DOCKER-USER -s <ip> -j REJECT --reject-with tcp-reset

