version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

  mariadb:
    build: ./requirements/mariadb
    restart: always
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
  wordpress_data:
    driver: local
