FROM debian:bookworm


RUN apt-get update && apt-get upgrade -y && apt-get install -y net-tools mariadb-server mariadb-client && apt-get clean

ENV MYSQL_ROOT_PASSWORD=rootpassword

COPY install.sh /usr/local/bin

RUN chmod +x /usr/local/bin/install.sh

EXPOSE 3306

ENTRYPOINT [ "/usr/local/bin/install.sh" ]