version: '3.8'

services:
  nginx:
    build: ./srcs/requirements/nginx
    image: nginx:new 
    container_name: MyNginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    volumes:
      - /home/${USER}/MyDatabase/Wordpress:/var/www/html
      - /home/${USER}/logs/nginx:/var/log/nginx

  wordpress:
    build: ./srcs/requirements/wordpress
    image: wordpress:new
    container_name: MyWordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - /home/${USER}/MyDatabase/Wordpress:/var/www/html
    env_file:
      - .env

  redis:
    build: ./srcs/requirements/bonus/redis
    image: redis:new
    container_name: MyRedis
    restart: always
    networks:
      - inception

  mariadb:
    build: ./srcs/requirements/mariadb
    image: mariadb:new
    container_name: MyMariaDB
    restart: always
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
  
  adminer:
    build: ./srcs/requirements/bonus/adminer
    image: adminer:new
    container_name: MyAdminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - inception

  ftp:
    build: ./srcs/requirements/bonus/ftp
    image: ftp:new
    container_name: MyFtp
    restart: always
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    networks:
      - inception
    volumes:
      - /home/${USER}/logs/vsftpd/vsftpd.log:/var/log/vsftpd.log
    env_file:
      - .env
    
  static-site:
    build: ./srcs/requirements/bonus/StaticWebSite
    image: static-site:new
    container_name: static-site
    restart: always
    ports:
      - "8081:80"
    networks:
      - inception

  fail2ban:
    build: ./srcs/requirements/bonus/fail2ban
    image: fail2ban:new
    container_name: MyFail2ban
    restart: always
    ports:
      - "2022:22"
    networks:
      - inception
    volumes:
      - /home/${USER}/logs/fail2ban:/var/log/fail2ban
      - /home/${USER}/logs/vsftpd:/var/log/vsftpd
      - /home/${USER}/logs/nginx:/var/log/nginx
    privileged: true

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      o: bind
      device: /home/${USER}/MyDatabase/MariaDB
      type: none