version: '3.8'

services:
  nginx:
    build: ./srcs/requirements/nginx
    image: nginx:new 
    container_name: MyNginx
    ports:
      - "443:443"
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html

  wordpress:
    build: ./srcs/requirements/wordpress
    image: wordpress:new
    container_name: MyWordpress
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env

  mariadb:
    build: ./srcs/requirements/mariadb
    image: mariadb:new
    container_name: MyMariaDB
    restart: always
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      o: bind
      device: /home/${USER}/MyDatabase/MariaDB
      type: none
  wordpress_data:
    driver_opts:
      o: bind
      device: /home/${USER}/MyDatabase/Wordpress
      type: none
