server.modules += ( "mod_fastcgi" )

fastcgi.server = (
  ".php" => ((
    "socket" => "/run/php/php8.2-fpm.sock",
    "broken-scriptfilename" => "enable"
  ))
)

server.document-root = "/var/www/html"
server.port = 8080
index-file.names = ("adminer.php")
server.username = "www-data"
server.groupname = "www-data"
